# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateXX <- function(X) {
    .Call('_LOCOM2_CalculateXX', PACKAGE = 'LOCOM2', X)
}

Newton_LOCOM2 <- function(rel_table, rel_table_sum, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var, step_rate = 1.0) {
    .Call('_LOCOM2_Newton_LOCOM2', PACKAGE = 'LOCOM2', rel_table, rel_table_sum, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var, step_rate)
}

perm_Newton_LOCOM2 <- function(rel_table, rel_table_sum, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var, step_rate = 1) {
    .Call('_LOCOM2_perm_Newton_LOCOM2', PACKAGE = 'LOCOM2', rel_table, rel_table_sum, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var, step_rate)
}

